menu:
  About: /about
  Archives: /archives
  Donate: /donate
  GitHub: https://github.com/TaxReformYYC

# duoshuo comment
duoshuo: false
duoshuo_name:

# disqus comment
disqus: false
disqus_shortname:

# google analytics
googleTrackId: UA-74042921-1
